### PR TITLE
nodelint.js from an npm installation

### PR DESCRIPTION
**Pull request by cliffano**
I added package.json and made some modification to nodelint.js so that it works from an npm installation.
I also replaced file manipulation utility functions with path module, and replaced the use of realpathSync since it doesn't work on node 0.2.0 when there's symlink pointing to an absolute path as part of the realpath (has been reported to node mailing list).
Thanks.

### CODE REVIEW

**Comment by mkitt** [comment]
Hi Cliffano.
I pulled those changes in from Sannis's earlier pull request. It looked like he had all of yours plus catching up with the latest from the master repository. Looked good to me, but let me know if there is anything missing. Great idea with the jslint xml reporter for Hudson. Can't wait to get that running on our CI boxes.

thanks!

**Comment by cliffano** [comment]
Ah, right, I didn't see the other pull request.

Would you be able to publish to npm registry? The instruction is available here http://github.com/isaacs/npm/blob/master/doc/developers.md#readme

I've been using the jslint xml reporter on Hudson, I like the fact that it's easy to hook up a reporter to nodelint.js (I wish jscoverage does the same thing).

Thank you.

**Comment by tav** [comment]
Hey guys,

Nice work, thank you!

Cliffano, could you add some documentation to the `README.md` file about installing via `npm` and a line about the new XML reporter? And, oh, please add yourself to the credits section too!

I'll take care of publishing to npm, but am thinking of simplifying the name to just "nodelint" — for both the package name and the binary name. What do you guys think?

And, oh, could you both add please yourself to a contributors field in the package.json?

— Cheers, tav

**Comment by tav** [comment]
I've updated the `package.json` file with the contributors and a few others changes — let me know re: the name change and if you're all okay with your details — I'll then do the `npm publish .`

Cheers!

**Comment by Sannis** [comment]
> I'll take care of publishing to npm, but am thinking of simplifying the name to just "nodelint" — for both the package name and the binary name. What do you guys think?

I agree. All looks good.

And yet, once a name containing 'node', may be worth making indent == 2 in the default configuration?

**Comment by mkitt** [comment]
I agree on the naming as well. I also committed in the indent == 2 in the default configuration. Everything looks good and ready to publish to me. 

thanks!

**Comment by cliffano** [comment]
I don't mind either way, `nodelint` is nice and it is not used by any other project yet.

**Comment by tav** [comment]
Alrighty, I've renamed everything to `nodelint` — including the repository name! I've also made a bunch of minor updates and published to npm.

This has been a really nice collaborative effort — thank you guys! Sorry for the inconvenience caused by the repository name change — do let me know if there are any issues. Cheers!

**Comment by mkitt** [comment]
Nice work and thanks to you as well! Its been a pleasure working with you guys. Nothing like github to bring a few coders together from around the globe. Anyone care to make an announcement on the node.js google groups board? I know there was a post a few months ago asking about this: http://bit.ly/cGM1AB

**Comment by cliffano** [comment]
I just tested the nodelint package from npm registry and found an error with path resolving, using node 0.2.0 and npm 0.2.0.
I'm looking at it now, so perhaps hold on the announcement yet.

Has anyone successfully tested the nodelint package from npm registry?

**Comment by tav** [comment]
Hmz, I seem to be able to install fine with node 0.2.0 and npm 0.2.0:

```
$ npm install nodelint
npm info it worked if it ends with ok
npm info version 0.2.0
npm info install nodelint@0.4.0
npm info activate nodelint@0.4.0
npm info build Success: nodelint@0.4.0
npm ok
```

What error message are you getting Cliff?

**Comment by tav** [comment]
I just did a completely fresh install of npm and it seems to work fine too:

```
$ npm install nodelint
npm info it worked if it ends with ok
npm info version 0.2.0
npm info fetch http://registry.npmjs.org/nodelint/-/nodelint@0.4.0.tgz
npm info install nodelint@0.4.0
npm info activate nodelint@0.4.0
npm info build Success: nodelint@0.4.0
npm ok
```

**Comment by tav** [comment]
Matthew, great idea with the announcement post. I see that you've been updating your javascript-nodelint.tmbundle repository — is that good to go too? I'll put together an email mentioning that too once Cliff gives us an okay with the npm install.

Also, perhaps the tmbundle repo could be renamed to just nodelint.tmbundle?

**Comment by cliffano** [comment]
tav, do you use a default installation of npm?

I found this error when I use npm with custom root and binroot (configurable in ~/.npmrc).
Error: ENOENT, No such file or directory 'path/to/jslint/jslint.js'

I think something must've behaved differently, when I installed nodelint.js from my branch yesterday, npm creates a shim that link the npm-binroot/nodelint.js to npm-root/.../nodelint.js, which is located on the same directory as jslint.js . (The relevant code is SCRIPT_DIRECTORY = path.dirname(fs.realpathSync(__filename));

Now, using the nodelint package from npm registry, npm-binroot/nodelint is not a shim, and it's the actual code. Hence it can no longer use path.dirname(fs.realpathSync(__filename)) since jslint.js is not placed in the same directory as nodelint.

**Comment by cliffano** [comment]
I suspect the bug is with fs.realpathSync, I reported another issue with fs.realpathSync to node mailing list a few days ago.
I'll keep looking.

Having said that, I think nodelint itself is fine, and the problem I'm having is quite an exception since most users will use default npm installation anyway.

**Comment by tav** [comment]
Yeah, with the `bin` in `package.json` set to `{nodelint: "./nodeline.js"}`, it seems that `npm` creates a shim. However, without the trailing `.js`, i.e. `{nodelint: "./nodeline"}`, then it just creates a direct symlink.

I'd added the `fs.realpathSync()` call back in earlier today to make it work when called by a symlink. What was the bug you'd found with the function? I couldn't find your post on the node mailing list.

Could you also put debug statements in the nodelint file that your installation symlinks to in order to find out what `__filename`, `fs.realpathSync(__filename)` and `SCRIPT_DIRECTORY` evaluate to?

**Comment by tav** [comment]
For the record, here are the symlinks that npm generates for me on `npm install nodelint`:

```
nodelint -> ./nodelint@0.4.0
nodelint@0.4.0 -> ./../lib/node/.npm/nodelint/0.4.0/package/nodelint
```

**Comment by mkitt** [comment]
Tav.
The TextMate Bundle is working great and good idea on the name change.

http://github.com/mkitt/nodelint.tmbundle

thanks

**Comment by cliffano** [comment]
Sorry for the late replies, I'm on GMT+10 .

tav, the debug statement showed that SCRIPT_DIRECTORY value is wrong. It turns out that the problem I was having only happens when the path to npm binroot includes a symlink.
This bug was fixed by isaacs on 686d9f9cc6688b4febf8ebc4655c1d1bc3515829, I've verified that the error no longer occurs in node 0.2.1 .
The other bug with fs.realpathSync that I reported is here http://prn.la/2d , this bug only affects symlink which points to absolute path instead of relative path, and it has been fixed in ry/master . This bug happens when path to npm binroot has such symlink.

Having said that, this issue affects all modules installed using npm, and not a nodelint-specific issue.

It looks like it's all clear for the announcement, tav.

**Comment by Sannis** [comment]
Thanks for your research about symlinks, it is important for me.

**Comment by cliffano** [comment]
Glad to know it's useful :).

**Comment by Sannis** [comment]
I think this pull request should be closed.

**Pull request merged**
