### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by jpolo**
I've been working on lots of improvements in nodelint such as :
- classification of the project (to be easily integrated in another program)
- jslint ported to a "requirable" module
- adapter pattern for formatters
- colored cli supported
- JSON config support

There are still some workarounds I hope you can help me to implement, like:
- more error handling
- more unit tests (ex: launcher)
- better args parsing

### CODE REVIEW

**Comment by tav** [comment]
Hey Julien,

Wow, that's quite a bit of work — which makes it even harder for me to say this, but I'm unfortunately going have to reject the patch =(

I really appreciate the effort that you've put into this, but by accepting the patch I would be severely compromising nodelint's key feature — its simplicity.

The current code base is very much of the minimalist Unix philosophy, whereas the patch is somewhat reminiscent of the over-engineering common in the Java world.

I hope I haven't offended you in any way and would love it if you would continue to engage with the project. But, right now, I really like how `nodelint` is only 200-odd lines of code and would like to keep it minimal.

mkitt, Sannis, what do you guys think?

**Comment by jpolo** [comment]
I forked your project because I needed some new functionnalities for my company. For example, I needed the integrability in another program like a unit test with a simple require('lint').Parse ). Like every open source community I just posted this patch to share my work and not just keep it to myself. I won't be offended if the patch is rejected, no problem...

Talking about simplicity, I don't think the code is really complex but I'm sure I improved the nodelint for the user. For example, instead of the --report=/my/path/to/lint/example/xml.js, the syntax is just --format=xml.
For html and xml output, the code can be generated as "pretty" for better debugging. I added an optional color support for better readability in the CLI reporter. (The eclipse console does not support colors so it can be disabled with --no-color option)

If the patch is rejected I will just publish my work on the npm with another name, I think it is a bit silly...

**Comment by tav** [comment]
The nice thing about the reporters is that you can simply pass the path to a custom one without needing a meta configuration file anywhere.

I do like some of the extra features in your formatters and it would be nice if you could rework them as new reporters.

— In any case, thanks for your work, tav

**Comment by Sannis** [comment]
It is difficult to make decision...

I've counted lines in current version of nodelint (approximately, with reporters): `993`. Most of Julien improvements are good (especially ability to require as lib and tests). And the doesn't cost much lines I think. Fro example, current version of nodeunit (with reporters and tests) have 2084 lines, but it is simple tool.

I think that one of reasons to dislike these patches may be the count and structure, so It may be better to rebase these commits in strong functional parts as 'tests', 'nodelint library extraction', 'new formatters', 'other features'.

So in general, I agree with this improvements.

**Pull request closed without merging**
