### PR TITLE
Add --xml-reporter and clean up walkDir

### PR DESCRIPTION
**Pull request by cliffano**
We have a number of projects which need to generate lint report in xml, and each one ends up having a nodelint reporter xml. This gets repetitive, so I think it would be great if nodelint itself supports this via --xml-reporter flag.

I also replaced walkDir snippet with file.walkSync, that's slightly cleaner.

### CODE REVIEW

**Comment by Sannis** [comment]
Nice idea about expose xml reporter to nodelint options.

I think we also can move reporters from `examples/reporters` to `lib/reporters` and use similar mechanism to avoid long --reporter values as in [nodeunit](https://github.com/caolan/nodeunit). It haves [index file for all reporters](https://github.com/caolan/nodeunit/blob/master/lib/reporters/index.js) and you can chose reporter by name rather than by reporter file name. In this case we can expose all reporters as --{name}-reporter options for nodelint. What is you opinion?

**Comment by cliffano** [comment]
That (--{name}-reporter) would be handy, +1 from me.

**Comment by Sannis** [comment]
I've created #21 for this. Anybody against this pull?

**Comment by tav** [comment]
LGTM.

Also, great idea on the `--{name}-reporter` flag.

**Pull request merged**
